from fastapi import APIRouter, Depends, status
from typing import Optional, Dict, Any
from app.schemas.demo import DemoStartRequest, DemoStatusResponse, DemoScenarioTrigger
from app.services.demo_simulator import simulator
from app.utils.logger import get_logger

logger = get_logger("api.demo")
router = APIRouter(prefix="/demo", tags=["Demo & Simulation System"])


@router.post("/start", response_model=DemoStatusResponse)
def start_demo_simulation(req: Optional[DemoStartRequest] = None):
    """
    Start the background industrial IoT simulation generator.
    Produces periodic normal, anomalous, degraded, and high-risk events through the end-to-end AI pipeline.
    """
    interval = req.interval_seconds if req else 3
    simulator.start(interval_seconds=interval)
    return simulator.get_status()


@router.post("/stop", response_model=DemoStatusResponse)
def stop_demo_simulation():
    """
    Stop the background simulation generator.
    """
    simulator.stop()
    return simulator.get_status()


@router.get("/status", response_model=DemoStatusResponse)
def get_demo_status():
    """
    Get the live status and total event count generated by the demo simulator.
    """
    return simulator.get_status()


@router.post("/trigger-step", status_code=status.HTTP_200_OK)
def trigger_single_scenario(trigger: DemoScenarioTrigger):
    """
    Manually trigger an individual simulation scenario on demand:
    `NORMAL_EVENT`, `ANOMALOUS_EVENT`, `MISSING_DATA_EVENT`, `CORRUPTED_DATA_EVENT`, `HIGH_RISK_EVENT`, `LOW_CONFIDENCE_EVENT`.
    """
    result = simulator.trigger_step(
        scenario_type=trigger.scenario_type,
        custom_overrides=trigger.custom_overrides
    )
    return {
        "message": f"Scenario '{trigger.scenario_type}' executed through pipeline successfully.",
        "result": result
    }
